// ============================================================
// Salon na we yon - Premium Theme System
// ============================================================

import type { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'ocean_blue',
    name: 'Ocean Blue',
    isPremium: false,
    colors: {
      primary: '#0077B6',
      primaryDark: '#005A8C',
      primaryLight: '#48CAE4',
      accent: '#FF6B35',
      background: '#F8F9FA',
      surface: '#FFFFFF',
      surfaceAlt: '#F0F2F5',
      text: '#1A1A2E',
      textSecondary: '#4A4A6A',
      textMuted: '#8E8EA0',
      border: '#E0E0E8',
      error: '#E63946',
      success: '#2D6A4F',
      warning: '#E9C46A',
      gradientStart: '#0077B6',
      gradientEnd: '#48CAE4',
    },
    effects: { glow: false, particles: false, shimmer: false, blur: false },
  },
  {
    id: 'sierra_leone',
    name: 'Sierra Leone 🇸🇱',
    isPremium: false,
    colors: {
      primary: '#007A3D',
      primaryDark: '#005A2D',
      primaryLight: '#4CAF50',
      accent: '#CE1126',
      background: '#F5FFF5',
      surface: '#FFFFFF',
      surfaceAlt: '#E8F5E9',
      text: '#1B5E20',
      textSecondary: '#388E3C',
      textMuted: '#81C784',
      border: '#C8E6C9',
      error: '#CE1126',
      success: '#007A3D',
      warning: '#FFC107',
      gradientStart: '#007A3D',
      gradientEnd: '#4CAF50',
    },
    effects: { glow: true, particles: false, shimmer: false, blur: false },
  },
  {
    id: 'sunset_gold',
    name: 'Sunset Gold',
    isPremium: false,
    colors: {
      primary: '#E8850C',
      primaryDark: '#C66A00',
      primaryLight: '#FFB74D',
      accent: '#5C6BC0',
      background: '#FFF8E1',
      surface: '#FFFFFF',
      surfaceAlt: '#FFF3CD',
      text: '#3E2723',
      textSecondary: '#6D4C41',
      textMuted: '#A1887F',
      border: '#FFE0B2',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57F17',
      gradientStart: '#E8850C',
      gradientEnd: '#FFB74D',
    },
    effects: { glow: true, particles: false, shimmer: true, blur: false },
  },
  {
    id: 'royal_purple',
    name: 'Royal Purple',
    isPremium: true,
    colors: {
      primary: '#7B2D8E',
      primaryDark: '#5C1A6E',
      primaryLight: '#AB47BC',
      accent: '#FFD54F',
      background: '#F3E5F5',
      surface: '#FFFFFF',
      surfaceAlt: '#EDE7F6',
      text: '#311B42',
      textSecondary: '#6A1B9A',
      textMuted: '#BA68C8',
      border: '#CE93D8',
      error: '#E53935',
      success: '#43A047',
      warning: '#FFB300',
      gradientStart: '#7B2D8E',
      gradientEnd: '#AB47BC',
    },
    effects: { glow: true, particles: true, shimmer: true, blur: false },
  },
  {
    id: 'midnight_dark',
    name: 'Midnight Dark',
    isPremium: true,
    colors: {
      primary: '#6C63FF',
      primaryDark: '#4A42D4',
      primaryLight: '#8B83FF',
      accent: '#FF6584',
      background: '#0D0D1A',
      surface: '#1A1A2E',
      surfaceAlt: '#16213E',
      text: '#EAEAEA',
      textSecondary: '#B0B0C0',
      textMuted: '#6C6C80',
      border: '#2A2A3E',
      error: '#FF4757',
      success: '#2ED573',
      warning: '#FFA502',
      gradientStart: '#6C63FF',
      gradientEnd: '#FF6584',
    },
    effects: { glow: true, particles: true, shimmer: true, blur: true },
  },
  {
    id: 'rose_pink',
    name: 'Rose Pink',
    isPremium: true,
    colors: {
      primary: '#E91E63',
      primaryDark: '#C2185B',
      primaryLight: '#F06292',
      accent: '#00BCD4',
      background: '#FCE4EC',
      surface: '#FFFFFF',
      surfaceAlt: '#F8BBD0',
      text: '#3E0E1E',
      textSecondary: '#880E4F',
      textMuted: '#EC407A',
      border: '#F48FB1',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#FF9800',
      gradientStart: '#E91E63',
      gradientEnd: '#F06292',
    },
    effects: { glow: true, particles: true, shimmer: false, blur: false },
  },
  {
    id: 'neon_cyber',
    name: 'Neon Cyber',
    isPremium: true,
    colors: {
      primary: '#00F5D4',
      primaryDark: '#00C4A7',
      primaryLight: '#5BFCE0',
      accent: '#F72585',
      background: '#0B0B1A',
      surface: '#141428',
      surfaceAlt: '#1E1E3A',
      text: '#E0E0FF',
      textSecondary: '#A0A0D0',
      textMuted: '#6060A0',
      border: '#2A2A50',
      error: '#FF0055',
      success: '#00FF88',
      warning: '#FFD600',
      gradientStart: '#00F5D4',
      gradientEnd: '#F72585',
    },
    effects: { glow: true, particles: true, shimmer: true, blur: true },
  },
  {
    id: 'forest_emerald',
    name: 'Forest Emerald',
    isPremium: true,
    colors: {
      primary: '#2E7D32',
      primaryDark: '#1B5E20',
      primaryLight: '#66BB6A',
      accent: '#FF8F00',
      background: '#E8F5E9',
      surface: '#FFFFFF',
      surfaceAlt: '#C8E6C9',
      text: '#1B5E20',
      textSecondary: '#388E3C',
      textMuted: '#81C784',
      border: '#A5D6A7',
      error: '#C62828',
      success: '#2E7D32',
      warning: '#F9A825',
      gradientStart: '#2E7D32',
      gradientEnd: '#66BB6A',
    },
    effects: { glow: true, particles: false, shimmer: true, blur: false },
  },
];

export function getTheme(id: string): Theme {
  return themes.find(t => t.id === id) || themes[0];
}

export function isThemeUnlocked(themeId: string, isSubscribed: boolean): boolean {
  const theme = themes.find(t => t.id === themeId);
  if (!theme) return false;
  if (!theme.isPremium) return true;
  return isSubscribed;
}
